// Mock Organizations & Locations Data for Magic Patterns UI Development

// Define the OrganizationBillingModel enum values as they appear in the schema
export enum OrganizationBillingModel {
  CONSOLIDATED = 'CONSOLIDATED', // One subscription for entire organization
  PER_LOCATION = 'PER_LOCATION', // Each location has its own subscription
  HYBRID = 'HYBRID', // Mix of consolidated and per-location
}

// Updated mock organizations to match the Organization model in schema.prisma
export const mockOrganizations = [
  {
    id: 'org_1',
    name: 'HealthCare Plus Clinic',
    description:
      'Modern healthcare facility providing comprehensive medical services with state-of-the-art equipment and experienced professionals.',
    email: 'admin@healthcareplus.com',
    phone: '+1555-0123',
    website: 'https://healthcareplus.com',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=200&h=200&fit=crop',
    businessRegistration: 'HC12345678',
    taxNumber: 'TAX987654321',
    billingAddress: '123 Medical Drive, New York, NY 10001, USA',
    billingModel: OrganizationBillingModel.CONSOLIDATED,
    timezone: 'America/New_York',
    defaultBookingWindow: 30,
    requiresApproval: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'org_2',
    name: 'Downtown Therapy Center',
    description:
      'Specialized mental health and physical therapy center serving the downtown community for over 15 years.',
    email: 'info@downtowntherapy.com',
    phone: '+1555-0124',
    website: 'https://downtowntherapy.com',
    logo: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=200&h=200&fit=crop',
    businessRegistration: 'DT98765432',
    taxNumber: 'TAX123456789',
    billingAddress: '789 Wellness Way, New York, NY 10003, USA',
    billingModel: OrganizationBillingModel.PER_LOCATION,
    timezone: 'America/New_York',
    defaultBookingWindow: 60,
    requiresApproval: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-20T14:15:00Z',
  },
  {
    id: 'org_3',
    name: 'Metro Dental Associates',
    description:
      'Full-service dental practice offering preventive, restorative, and cosmetic dentistry in a comfortable environment.',
    email: 'appointments@metrodental.com',
    phone: '+1555-0125',
    website: 'https://metrodental.com',
    logo: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=200&h=200&fit=crop',
    businessRegistration: 'MDA5678901',
    taxNumber: 'TAX567890123',
    billingAddress: '101 Smile Street, New York, NY 10004, USA',
    billingModel: OrganizationBillingModel.HYBRID,
    timezone: 'America/New_York',
    defaultBookingWindow: 45,
    requiresApproval: false,
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-22T16:45:00Z',
  },
];

// Update mock locations to align with the Location model
export const mockLocations = [
  {
    id: 'loc_1',
    organizationId: 'org_1',
    name: 'HealthCare Plus - Main Clinic',
    address: '123 Medical Drive',
    city: 'New York',
    state: 'NY',
    postalCode: '10001',
    country: 'USA',
    phone: '+1555-0123-1',
    email: 'main@healthcareplus.com',
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '17:00' },
      saturday: { open: '09:00', close: '14:00' },
      sunday: { open: null, close: null },
    },
    timezone: 'America/New_York',
    capacity: 25,
    facilities: ['X-Ray', 'Lab', 'Pharmacy'],
    accessibilityInfo:
      'Wheelchair accessible entrance and restrooms, elevator access to all floors',
    googlePlaceId: 'ChIJa1D_umVZwokRDHnHsU6l_3I',
    coordinates: { lat: 40.7128, lng: -74.006 },
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'loc_2',
    organizationId: 'org_1',
    name: 'HealthCare Plus - Downtown Branch',
    address: '456 Central Avenue',
    city: 'New York',
    state: 'NY',
    postalCode: '10002',
    country: 'USA',
    phone: '+1555-0123-2',
    email: 'downtown@healthcareplus.com',
    operatingHours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: null, close: null },
      sunday: { open: null, close: null },
    },
    timezone: 'America/New_York',
    capacity: 15,
    facilities: ['Lab'],
    accessibilityInfo: 'Wheelchair accessible entrance',
    googlePlaceId: 'ChIJhR2cFqpZwokRPU7OIGh4-rM',
    coordinates: { lat: 40.7168, lng: -73.9973 },
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-16T11:45:00Z',
  },
  {
    id: 'loc_3',
    organizationId: 'org_2',
    name: 'Downtown Therapy Center - Main Office',
    address: '789 Wellness Way',
    city: 'New York',
    state: 'NY',
    postalCode: '10003',
    country: 'USA',
    phone: '+1555-0124-1',
    email: 'office@downtowntherapy.com',
    operatingHours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '18:00' },
      saturday: { open: '10:00', close: '15:00' },
      sunday: { open: null, close: null },
    },
    timezone: 'America/New_York',
    capacity: 10,
    facilities: ['Meditation Room', 'Group Therapy Space'],
    accessibilityInfo: 'Wheelchair accessible, sensory-friendly waiting area',
    googlePlaceId: 'ChIJE9on3F1ZwokRJDIHrcCrvLQ',
    coordinates: { lat: 40.7308, lng: -73.9973 },
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-20T14:15:00Z',
  },
  {
    id: 'loc_4',
    organizationId: 'org_3',
    name: 'Metro Dental Associates - Main Office',
    address: '101 Smile Street',
    city: 'New York',
    state: 'NY',
    postalCode: '10004',
    country: 'USA',
    phone: '+1555-0125-1',
    email: 'office@metrodental.com',
    operatingHours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: { open: '09:00', close: '13:00' },
      sunday: { open: null, close: null },
    },
    timezone: 'America/New_York',
    capacity: 8,
    facilities: ['X-Ray', 'Dental Lab'],
    accessibilityInfo: 'Wheelchair accessible',
    googlePlaceId: 'ChIJaXQRs6lZwokRslv4kLBB9-k',
    coordinates: { lat: 40.7033, lng: -74.017 },
    isActive: true,
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-22T16:45:00Z',
  },
];

export const mockOrganizationTypes = [
  'CLINIC',
  'HOSPITAL',
  'THERAPY_CENTER',
  'DENTAL_OFFICE',
  'URGENT_CARE',
  'SPECIALTY_PRACTICE',
] as const;
