// Mock Service Providers & Services Data for Magic Patterns UI Development

// First define the service provider types
export const mockServiceProviderTypes = [
  {
    id: 'type_1',
    name: 'Family Physician',
    description: 'General medical practitioner for all ages',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'type_2',
    name: 'Psychologist',
    description: 'Mental health professional',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'type_3',
    name: 'Dentist',
    description: 'Oral health professional',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
] as const;

// Define services according to the schema
export const mockServices = [
  {
    id: 'service_1',
    name: 'Annual Physical Exam',
    description:
      'Comprehensive annual health assessment including vital signs, lab work, and preventive care screening.',
    serviceProviderTypeId: 'type_1',
    displayPriority: 1,
    defaultDuration: 60, // in minutes
    defaultPrice: 2500.0, // Decimal in schema
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'service_2',
    name: 'Sick Visit',
    description:
      'Evaluation and treatment for acute illness or injury. Same-day appointments often available.',
    serviceProviderTypeId: 'type_1',
    displayPriority: 2,
    defaultDuration: 30,
    defaultPrice: 1500.0,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'service_3',
    name: 'Individual Therapy Session',
    description:
      'One-on-one counseling session using evidence-based therapeutic approaches tailored to your specific needs.',
    serviceProviderTypeId: 'type_2',
    displayPriority: 1,
    defaultDuration: 50,
    defaultPrice: 1800.0,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'service_4',
    name: 'Couples Counseling',
    description:
      'Relationship counseling for couples looking to improve communication and resolve conflicts.',
    serviceProviderTypeId: 'type_2',
    displayPriority: 2,
    defaultDuration: 75,
    defaultPrice: 2200.0,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'service_5',
    name: 'Dental Cleaning',
    description:
      'Professional teeth cleaning to remove plaque and tartar, plus oral health assessment.',
    serviceProviderTypeId: 'type_3',
    displayPriority: 1,
    defaultDuration: 45,
    defaultPrice: 1200.0,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'service_6',
    name: 'Dental Filling',
    description:
      'Treatment for dental cavities using composite resin fillings that match your natural tooth color.',
    serviceProviderTypeId: 'type_3',
    displayPriority: 2,
    defaultDuration: 60,
    defaultPrice: 1800.0,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
] as const;

// Define service providers with proper connections to services
export const mockServiceProviders = [
  {
    id: 'provider_1',
    name: 'Dr. Michael Smith',
    userId: 'user_2',
    serviceProviderTypeId: 'type_1',
    bio: 'Board-certified family physician with over 12 years of experience providing comprehensive healthcare to patients of all ages. Specializes in preventive care, chronic disease management, and patient education.',
    email: 'michael.smith@medicalpractice.com',
    whatsapp: '+27123456789',
    status: 'ACTIVE',
    verifiedAt: '2024-01-15T10:00:00Z',
    timezone: 'Africa/Johannesburg',
    image:
      'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&h=300&fit=crop&crop=face',
    languages: ['English', 'Afrikaans'],
    billingType: 'MEDICAL_AID_AND_PRIVATE',
    website: 'https://drmichaelsmith.co.za',
    averageRating: 4.8,
    totalReviews: 156,
    googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
    googleBusinessAccount: 'dr.michael.smith.practice',
    canBeBookedByOrg: false,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-25T15:30:00Z',
  },
  {
    id: 'provider_2',
    name: 'Dr. Emma Williams',
    userId: 'user_4',
    serviceProviderTypeId: 'type_2',
    bio: 'Licensed clinical psychologist specializing in anxiety, depression, and trauma therapy. Uses evidence-based approaches including CBT and EMDR to help clients achieve lasting positive change.',
    email: 'emma.williams@therapy.co.za',
    whatsapp: '+27987654321',
    status: 'ACTIVE',
    verifiedAt: '2024-01-18T14:30:00Z',
    timezone: 'Africa/Johannesburg',
    image:
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&h=300&fit=crop&crop=face',
    languages: ['English', 'French'],
    billingType: 'PRIVATE_ONLY',
    website: 'https://emmawilliamstherapy.co.za',
    averageRating: 4.9,
    totalReviews: 203,
    googlePlaceId: 'ChIJrTLr-GyuEmsRBfy61i59si0',
    googleBusinessAccount: 'emma.williams.therapy',
    canBeBookedByOrg: true,
    createdAt: '2024-01-12T08:00:00Z',
    updatedAt: '2024-01-26T12:45:00Z',
  },
  {
    id: 'provider_3',
    name: 'Dr. James Chen',
    userId: 'user_6',
    serviceProviderTypeId: 'type_3',
    bio: 'Experienced general dentist committed to providing gentle, comprehensive dental care. Specializes in restorative dentistry, preventive care, and cosmetic procedures with a focus on patient comfort.',
    email: 'james.chen@dentalcare.co.za',
    whatsapp: '+27456789123',
    status: 'ACTIVE',
    verifiedAt: '2024-01-20T09:15:00Z',
    timezone: 'Africa/Johannesburg',
    image:
      'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&h=300&fit=crop&crop=face',
    languages: ['English', 'Mandarin'],
    billingType: 'ALL',
    website: 'https://jameschendental.co.za',
    averageRating: 4.7,
    totalReviews: 89,
    googlePlaceId: 'ChIJ2eUgeAK6EmsRqRW2rIhGLvM',
    googleBusinessAccount: 'james.chen.dental',
    canBeBookedByOrg: false,
    createdAt: '2024-01-14T09:30:00Z',
    updatedAt: '2024-01-24T16:20:00Z',
  },
] as const;

// Define the service availability configurations to connect providers with services
export const mockServiceAvailabilityConfigs = [
  {
    id: 'config_1',
    serviceId: 'service_1',
    serviceProviderId: 'provider_1',
    duration: 60, // in minutes
    price: 2500.0,
    isOnlineAvailable: true,
    isInPerson: true,
    location: 'Main Office',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'config_2',
    serviceId: 'service_2',
    serviceProviderId: 'provider_1',
    duration: 30,
    price: 1500.0,
    isOnlineAvailable: true,
    isInPerson: true,
    location: 'Main Office',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'config_3',
    serviceId: 'service_3',
    serviceProviderId: 'provider_2',
    duration: 50,
    price: 1800.0,
    isOnlineAvailable: true,
    isInPerson: true,
    location: 'Therapy Center',
    createdAt: '2024-01-12T08:00:00Z',
    updatedAt: '2024-01-12T08:00:00Z',
  },
  {
    id: 'config_4',
    serviceId: 'service_4',
    serviceProviderId: 'provider_2',
    duration: 75,
    price: 2200.0,
    isOnlineAvailable: true,
    isInPerson: true,
    location: 'Therapy Center',
    createdAt: '2024-01-12T08:00:00Z',
    updatedAt: '2024-01-12T08:00:00Z',
  },
  {
    id: 'config_5',
    serviceId: 'service_5',
    serviceProviderId: 'provider_3',
    duration: 45,
    price: 1200.0,
    isOnlineAvailable: false,
    isInPerson: true,
    location: 'Dental Office',
    createdAt: '2024-01-14T09:30:00Z',
    updatedAt: '2024-01-14T09:30:00Z',
  },
  {
    id: 'config_6',
    serviceId: 'service_6',
    serviceProviderId: 'provider_3',
    duration: 60,
    price: 1800.0,
    isOnlineAvailable: false,
    isInPerson: true,
    location: 'Dental Office',
    createdAt: '2024-01-14T09:30:00Z',
    updatedAt: '2024-01-14T09:30:00Z',
  },
] as const;

export const mockServiceCategories = [
  'Preventive Care',
  'Acute Care',
  'Chronic Care Management',
  'Mental Health',
  'Preventive Dental',
  'Restorative Dental',
  'Cosmetic Dental',
  'Emergency Care',
  'Specialist Consultation',
] as const;
